### ISSUE TITLE
GET with authentication

### ISSUE THREAD

**Issue by emanueleffe** [ropensci/ckanr#106]
Hi, I'd like to use your library in an internal project with a protected Apache HTTP connection but it seems that is impossible to set up a connection like that.
Using httr library I can connect (and then get the dataset) calling the following method: GET(requestURL, authenticate(username,password, type = "basic")).
Is it possible to implement something like ckanr_setup(url, username, password) that works with authentication?

Thank you in advance.

**Comment by sckott** [comment]
thanks for your question @emanueleffe 

you should be able to pass in httr options/fxns through `...` in each fxn. e.g., 

```r
package_search(q = '*:*', authenticate(username, pwd))
```

let me know if that works

**Comment by sckott** [comment]
hmm, okay, thanks. I think I don't have it setup internally so that you can pass in other curl options. 

I think we can do it this way: 

```r
library(ckanr)
library(httr)
set_config(authenticate(username, password))
set_config(verbose())
package_search(q = "*:*")
```

The `verbose()` option is not required, but lets you see if authentication is working, look for a header like (the username and password is converted to a uuid so the details aren't seen by a 3rd party)

```
-> Authorization: Basic Zm9vOmJhcg==
```

let me know if that works.

**Comment by emanueleffe** [comment]
Thank you again for your response. I just tried and **it works** with `set_config(authenticate(username, password))`! 

Thank you again for your precious help!

**Comment by sckott** [comment]
glad it works
