### ISSUE TITLE
How to update extras using package_patch?

### ISSUE THREAD

**Issue by smartgamer** [ropensci/ckanr#147]
I tried to update extras using package_patch, but it doesn't work. Anybody succeed in updating it? or this function is not included in ckanr?

**Comment by smartgamer** [comment]
@sckott I saw an issue raised by you when searching this site. Has this problem been solved?

**Comment by sckott** [comment]
yes, here https://github.com/ropensci/ckanr/issues/94 we discuss extras in `package_patch` - unfortunately, i've never got it to work, so haven't added it to the function because I can't be sure that it's working correclty. 

`package_create` does have `extras` parameter though, can you try `extras` in `package_create` on your instance and see if at least that works?

**Comment by smartgamer** [comment]
package_create will work but it's used to create package instead of update it. I already have a package uploaded and want to update it.

Is there any other way to get around this? or use python?

**Comment by sckott** [comment]
yes i know you already have a package created, but I want to see if extras works with that function, can you try to create a package and use extras to see if that works?

**Comment by smartgamer** [comment]
That always works. But I want to update instead of starting from scratch. Thanks


On Nov 14, 2019, at 7:57 PM, Scott Chamberlain <notifications@github.com> wrote:

﻿

yes i know you already have a package created, but I want to see if extras works with that function, can you try to create a package and use extras to see if that works?

**Comment by sckott** [comment]
this should be fixed now
