### ISSUE TITLE
Including option for txt-files in ckan_fetch()

### ISSUE THREAD

**Issue by hannaboe** [ropensci/ckanr#160]
I was wondering if it would be possible to include an option for loading txt-files into R in `ckan_fetch()`? So far, txt-files can't be downloaded if `store = session`. 

I could work on a PR.

**Comment by sckott** [comment]
Thanks @hannaboe 

@sharlagelfand can you advise here?

**Comment by sharlagelfand** [comment]
my initial thoughts are that `txt` files aren't straightforward flat files in the way things like CSVs or excel files are (even though those can be pretty questionable too!). I have seen some cases where they contain actual data, but on the Toronto portal I'd say most txt files are READMEs describing the data, not actual data themselves, so they tend to have some funky formatting

looking at a couple different `txt` files from Toronto portal, leaving CKAN/ckanr out of it and just thinking about reading the files:

source: https://open.toronto.ca/dataset/solid-waste-pickup-schedule/
resource: https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/7b70189a-aede-42f1-b092-8708fa4f5fc3/resource/e4211f49-611f-438c-a444-aaa7f3f84117/download/pickup-schedule-2020.txt

this one works fine enough with read.table:

``` r
tmp <- tempfile(fileext = ".txt")

download.file("https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/7b70189a-aede-42f1-b092-8708fa4f5fc3/resource/e4211f49-611f-438c-a444-aaa7f3f84117/download/pickup-schedule-2020.txt", tmp)

head(read.table(tmp))
#>            V1           V2       V3      V4        V5        V6            V7
#> 1    Calendar WeekStarting GreenBin Garbage Recycling YardWaste ChristmasTree
#> 2 MondayNight     01/06/20        M       M         0         0             M
#> 3 MondayNight     01/13/20        M       0         M         0             0
#> 4 MondayNight     01/20/20        M       M         0         0             M
#> 5 MondayNight     01/27/20        M       0         M         0             0
#> 6 MondayNight     02/03/20        M       M         0         0             0
```

source: https://open.toronto.ca/dataset/building-permits-signs/
resource: https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/5a19a44e-5fbe-4b3f-9246-4946de37fff5/resource/c238eb23-474a-445f-8037-50d440502219/download/sign-permit-readme.txt

this one does not, because it has a line describing the data first. Could use `readLines()` but then the table formatting is lost:

``` r
tmp <- tempfile(fileext = ".txt")

download.file("https://ckan0.cf.opendata.inter.prod-toronto.ca/download_resource/c238eb23-474a-445f-8037-50d440502219", tmp)

read.table(tmp)
#> Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 2 did not have 8 elements
read.table(tmp, header = FALSE)
#> Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 2 did not have 8 elements

# Would probably have to use readLines() instead - but then the table formatting is lost
head(readLines(tmp))
#> Warning in readLines(tmp): incomplete final line found on '/var/folders/j5/
#> d1hztrys1xzg_8557yh176300000gn/T//Rtmp1dgS5N/filee0a53eddf50e.txt'
#> [1] "Format of the Sign Permit Open data dataset "                                                              
#> [2] ""                                                                                                          
#> [3] "permit #            \tLast two digits of the calendar year plus              Format is 99 999999          "
#> [4] "                           Sequence number generated by IBMS system               "                        
#> [5] "type\t      \t      Permit type\tFirst party or third party"                                               
#> [6] "street#\t\t\tAddress \x96 street number   "
```

makes me think that choosing a function for reading in txt files is not as straight forward as the other formats - could go for `read.table()` and return some custom error if that errors out?

**Comment by hannaboe** [comment]
This sounds good to me.

**Comment by sckott** [comment]
Sounds good to me @sharlagelfand
